// Tags DB removed for static build. Provide stubs.
export const getAllTags = async (): Promise<any[]> => [];
export const createTag = async (): Promise<void> => {};
export const updateTag = async (): Promise<void> => {};
export const deleteTag = async (): Promise<void> => {};
export const getTagsForPost = async (): Promise<any[]> => [];
export const addTagToPost = async (): Promise<void> => {};
export const removeTagFromPost = async (): Promise<void> => {};
export const ensureTags = async (): Promise<number[]> => [];
export const setTagsForPost = async (): Promise<void> => {};
